version: '2'
services:
  ambari-server-database:
    image: library/postgres:9.6
    environment:
      POSTGRES_USER: ambari
      POSTGRES_PASSWORD: bigdata
      POSTGRES_DB: ambari
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ambari=server
  ambari-server:
    privileged: true
    image: grozeille/ambari-server:2.5.1.0-v1
    stdin_open: true
    tty: true
    ports:
    - 8081:8080/tcp
    links:
    - ambari-server-database:ambari-server-database
    command:
    - systemd.setenv=USE_CONSUL_DNS=false
    - systemd.setenv=POSTGRES_DB=ambari-server-database
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ambari=server
  ambari-agent-namenode:
    privileged: true
    image: grozeille/ambari-agent:2.5.1.0-v1
    stdin_open: true
    volumes:
    - /mnt/sda1/hadoop:/hadoop
    tty: true
    ports:
    - 50070:50070/tcp
    links:
    - ambari-server:ambari-server
    command:
    - systemd.setenv=USE_CONSUL_DNS=false
    - systemd.setenv=AMBARI_SERVER_ADDR=ambari-server
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: hadoop=master
  ambari-agent-secondarynamenode:
    privileged: true
    image: grozeille/ambari-agent:2.5.1.0-v1
    stdin_open: true
    volumes:
    - /mnt/sda1/hadoop:/hadoop
    tty: true
    links:
    - ambari-server:ambari-server
    command:
    - systemd.setenv=USE_CONSUL_DNS=false
    - systemd.setenv=AMBARI_SERVER_ADDR=ambari-server
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: hadoop=master
  ambari-agent-resourcemanager:
    privileged: true
    image: grozeille/ambari-agent:2.5.1.0-v1
    stdin_open: true
    volumes:
    - /mnt/sda1/hadoop:/hadoop
    tty: true
    ports:
    - 8088:8088/tcp
    - 19888:19888/tcp
    links:
    - ambari-server:ambari-server
    command:
    - systemd.setenv=USE_CONSUL_DNS=false
    - systemd.setenv=AMBARI_SERVER_ADDR=ambari-server
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: hadoop=data
  ambari-agent-spark:
    privileged: true
    image: grozeille/ambari-agent:2.5.1.0-v1
    stdin_open: true
    volumes:
    - /mnt/sda1/hadoop:/hadoop
    tty: true
    ports:
    - 18080:18080/tcp
    - 8998:8998/tcp
    links:
    - ambari-server:ambari-server
    command:
    - systemd.setenv=USE_CONSUL_DNS=false
    - systemd.setenv=AMBARI_SERVER_ADDR=ambari-server
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: hadoop=data
  ambari-agent-zookeeper:
    privileged: true
    image: grozeille/ambari-agent:2.5.1.0-v1
    stdin_open: true
    volumes:
    - /mnt/sda1/hadoop:/hadoop
    tty: true
    links:
    - ambari-server:ambari-server
    command:
    - systemd.setenv=USE_CONSUL_DNS=false
    - systemd.setenv=AMBARI_SERVER_ADDR=ambari-server
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: hadoop=data
  ambari-agent-hive-database:
    image: library/postgres:9.6
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: hive
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: hadoop=data
  ambari-agent-hive:
    privileged: true
    image: grozeille/ambari-agent:2.5.1.0-v1
    stdin_open: true
    volumes:
    - /mnt/sda1/hadoop:/hadoop
    tty: true
    links:
    - ambari-server:ambari-server
    - ambari-agent-hive-database:ambari-agent-hive-database
    command:
    - systemd.setenv=USE_CONSUL_DNS=false
    - systemd.setenv=AMBARI_SERVER_ADDR=ambari-server
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: hadoop=data
  ambari-agent-datanode:
    privileged: true
    image: grozeille/ambari-agent:2.5.1.0-v1
    stdin_open: true
    volumes:
    - /mnt/sda1/hadoop:/hadoop
    tty: true
    ports:
    - 8042:8042/tcp
    - 50075:50075/tcp
    links:
    - ambari-server:ambari-server
    command:
    - systemd.setenv=USE_CONSUL_DNS=false
    - systemd.setenv=AMBARI_SERVER_ADDR=ambari-server
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: hadoop=data