version: '2'
services:
  ambari-server-database:
    image: library/postgres:9.6
    environment:
      POSTGRES_USER: ambari
      POSTGRES_PASSWORD: bigdata
      POSTGRES_DB: ambari
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ambari=server
  ambari-server:
    privileged: true
    image: hortonworks/ambari-server
    stdin_open: true
    tty: true
    ports:
    - 8081:8080/tcp
    links:
    - ambari-server-database:ambari-server-database
    command:
    - systemd.setenv=USE_CONSUL_DNS=false
    - systemd.setenv=POSTGRES_DB=ambari-server-database
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ambari=server
  ambari-agent-namenode:
    privileged: true
    image: hortonworks/ambari-agent
    stdin_open: true
    tty: true
    ports:
    - 50070:50070/tcp
    links:
    - ambari-server:ambari-server
    command:
    - systemd.setenv=USE_CONSUL_DNS=false
    - systemd.setenv=AMBARI_SERVER_ADDR=ambari-server
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: hadoop=master
  ambari-agent-secondarynamenode:
    privileged: true
    image: hortonworks/ambari-agent
    stdin_open: true
    tty: true
    links:
    - ambari-server:ambari-server
    command:
    - systemd.setenv=USE_CONSUL_DNS=false
    - systemd.setenv=AMBARI_SERVER_ADDR=ambari-server
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: hadoop=master
  ambari-agent-resourcemanager:
    privileged: true
    image: hortonworks/ambari-agent
    stdin_open: true
    tty: true
    ports:
    - 8088:8088/tcp
    links:
    - ambari-server:ambari-server
    command:
    - systemd.setenv=USE_CONSUL_DNS=false
    - systemd.setenv=AMBARI_SERVER_ADDR=ambari-server
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: hadoop=master
  ambari-agent-zookeeper:
    privileged: true
    image: hortonworks/ambari-agent
    stdin_open: true
    tty: true
    links:
    - ambari-server:ambari-server
    command:
    - systemd.setenv=USE_CONSUL_DNS=false
    - systemd.setenv=AMBARI_SERVER_ADDR=ambari-server
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: hadoop=master
  ambari-agent-datanode:
    privileged: true
    image: hortonworks/ambari-agent
    stdin_open: true
    tty: true
    links:
    - ambari-server:ambari-server
    command:
    - systemd.setenv=USE_CONSUL_DNS=false
    - systemd.setenv=AMBARI_SERVER_ADDR=ambari-server
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: hadoop=data